/**
 * Fallback for NEXT_PUBLIC_API_URL when migrating from legacy env vars
 */
function getApiUrlFallback() {
	return (
		process.env.NEXT_PUBLIC_SONARAEM_API_URL ??
		process.env.SONARAEM_BETTER_AUTH_URL ??
		process.env.SONARAEM_CORS_ORIGIN ??
		process.env.NEXT_PUBLIC_SONARAEM_APP_URL
	);
}

/**
 * Server-side runtime env with fallbacks (for api preset, server routes)
 */
export function createServerRuntimeEnv(): NodeJS.ProcessEnv {
	return {
		...process.env,
		NEXT_PUBLIC_SONARAEM_API_URL: getApiUrlFallback(),
		NEXT_PUBLIC_SONARAEM_ALLOWED_ORIGIN:
			process.env.NEXT_PUBLIC_SONARAEM_ALLOWED_ORIGIN ??
			process.env.SONARAEM_CORS_ORIGIN ??
			process.env.SONARAEM_BETTER_AUTH_URL ??
			getApiUrlFallback(),
	};
}

/**
 * Helper to create runtimeEnv object for Next.js presets
 * MUST use literal property access for Next.js bundling to work
 */
export function createNextjsRuntimeEnv() {
	return {
		VERCEL: process.env.VERCEL,
		SONARAEM_DATABASE_URL: process.env.SONARAEM_DATABASE_URL,
		NEXT_PUBLIC_SONARAEM_NODE_ENV: process.env.NEXT_PUBLIC_SONARAEM_NODE_ENV,
		NEXT_PUBLIC_SONARAEM_API_URL: getApiUrlFallback(),
		NEXT_PUBLIC_SONARAEM_ALLOWED_ORIGIN:
			process.env.NEXT_PUBLIC_SONARAEM_ALLOWED_ORIGIN ??
			process.env.SONARAEM_CORS_ORIGIN ??
			process.env.SONARAEM_BETTER_AUTH_URL,
		NEXT_PUBLIC_SONARAEM_WEB_URL:
			process.env.NEXT_PUBLIC_SONARAEM_WEB_URL ??
			process.env.SONARAEM_BETTER_AUTH_URL ??
			process.env.SONARAEM_CORS_ORIGIN,
		NEXT_PUBLIC_SONARAEM_DASHBOARD_URL:
			process.env.NEXT_PUBLIC_SONARAEM_DASHBOARD_URL,
		NEXT_PUBLIC_SONARAEM_ADMIN_URL: process.env.NEXT_PUBLIC_SONARAEM_ADMIN_URL,
		SONARAEM_SPOTIFY_CLIENT_ID: process.env.SONARAEM_SPOTIFY_CLIENT_ID,
		SONARAEM_RESEND_API_KEY: process.env.SONARAEM_RESEND_API_KEY,
		SONARAEM_EMAIL_FROM: process.env.SONARAEM_EMAIL_FROM,
		SONARAEM_EMAIL_REPLY_TO: process.env.SONARAEM_EMAIL_REPLY_TO,
		SONARAEM_RESEND_WEBHOOK_SECRET: process.env.SONARAEM_RESEND_WEBHOOK_SECRET,
		SONARAEM_OTEL_SERVICE_NAME: process.env.SONARAEM_OTEL_SERVICE_NAME,
		SONARAEM_OTEL_SAMPLING_RATE: process.env.SONARAEM_OTEL_SAMPLING_RATE,
		SONARAEM_OTEL_ENABLED: process.env.SONARAEM_OTEL_ENABLED,
		SONARAEM_OTEL_EXPORTER_OTLP_ENDPOINT:
			process.env.SONARAEM_OTEL_EXPORTER_OTLP_ENDPOINT,
		SONARAEM_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:
			process.env.SONARAEM_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT,
		SONARAEM_OTEL_EXPORTER_OTLP_METRICS_ENDPOINT:
			process.env.SONARAEM_OTEL_EXPORTER_OTLP_METRICS_ENDPOINT,
		SONARAEM_OTEL_EXPORTER_OTLP_LOGS_ENDPOINT:
			process.env.SONARAEM_OTEL_EXPORTER_OTLP_LOGS_ENDPOINT,
		SONARAEM_OTEL_EXPORTER_OTLP_HEADERS:
			process.env.SONARAEM_OTEL_EXPORTER_OTLP_HEADERS,
		SONARAEM_OTEL_EXPORTER_OTLP_PROTOCOL:
			process.env.SONARAEM_OTEL_EXPORTER_OTLP_PROTOCOL,
		SONARAEM_OTEL_EXPORTER_OTLP_COMPRESSION:
			process.env.SONARAEM_OTEL_EXPORTER_OTLP_COMPRESSION,
	} as const;
}
